<?php

class Quoter {

    private $quotes = array();

    public function __construct()
    {
        $this->quotes = $this->fillQuotes();
        return $this;
    }

    public function select( $id = null ) {
        $quote_ct = count($this->quotes);
        if ( is_null($id) || !is_numeric ($id) || $id > $quote_ct  ) {
            $id = rand(1, $quote_ct);
        } 
        return $this->quotes[$id];
    }

    public function getQuoteCt()
    {
        return count($this->quotes);
    }

    private function fillQuotes()
    {
        return ["","Books serve to show a man that those original thoughts of his aren't very new after all.",
"I did the very best I can without reading too much into the unjust, negative criticisms made about me. If the end brings me out all right, then what is said about me won't matter. If the end brings me out wrong, then 10 angels swearing I was right would make no difference",
"My Best Friend is a person who will give me a book I have not read.",
"You can please all of the people some of the time or some of the people all of the time, but you can never please all of the people all of the time.",
"But what is happiness except the simple harmony between a man and the life he leads?",
"Creativity is knowing how to hide your sources.",
"Everybody is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing it is stupid.",
"It's not that I'm so smart, it's just that I stay with problems longer I have no special talents. I am only passionately curious",
"Life is like riding a bicycle. To keep your balance, you must keep moving",
"The true sign of intelligence is not knowledge but imagination",
"Try not to become a man of success, but rather try to become a man of value.",
"For the happy man prayer is only a jumble of words, until the day when sorrow comes to explain to him the sublime language by means of which he speaks to God. - The Count of Monte Cristo",
"Learning does not make one learned: there are those who have knowledge and those who have understanding. The first requires memory and the second philosophy",
"Life is a storm, my young friend. You will bask in the sunlight one moment, be shattered on the rocks the next. What makes you a man is what you do when that storm comes.",
"The difference between treason and patriotism is only a matter of dates.",
"There is neither happiness nor misery in the world; there is only the comparison of one state with another, nothing more. He who has felt the deepest grief is best able to experience supreme happiness.",
"This piece of iron which he had been allowed to keep aroused a more profound wave of gratitude towards Heaven in his heart than the greatest blessings that he experienced in his life outside of prison - The Count of Monte Cristo, describing Edmond Dantes when he luckily finds a piece of iron to dig a hole out of his prison",
"Those born to wealth, and who have the means of gratifying every wish, know not what is the real happiness of life, just as those who have been tossed on the stormy waters of the ocean on a few frail planks can alone realize the blessings of fair weather.-  The Count of Monte Cristo",
"A few observations and much reasoning lead to error. Many observations and a little reasoning lead to truth.",
"Don't wait around for other people to be happy for you. Any happiness you get you've got to make yourself",
"Do your duty and a little more and the future will take care of itself",
"People who are unable to motivate themselves must be content with mediocrity, no matter how impressive their other talents.",
"The average person puts only 25% of his energy and ability into his work. The world takes off its hat to those who put in more than 50% of their capacity, and stands on its head for those few and far between souls who devote 100%",
"There is little success where there is little laughter",
"Think of yourself as on the threshold of unparalleled success. A whole, clear, glorious life lies before you. Achieve! Achieve!",
"Using the power of decision gives you the capacity to get past any excuse to change any and every part of your life in an instant.",
"Here's to the crazy ones. The misfits. The rebels. The troublemakers. The round pegs in the square holes. The ones who see things differently. They're not fond of rules. And they have no respect for the status quo. You can quote them, disagree with them, glorify or vilify them. About the only thing you can't do is ignore them. Because they change things. They push the human race forward. And while some may see them as the crazy ones, we see genius. Because the people who are crazy enough to think they can change the world, are the ones who do",
"Anybody can become angry - that is easy, but to be angry with the right person and to the right degree and at the right time and for the right purpose, and in the right way, that is not within everybody's power and is not easy",
"If you wish to have a quality you don't have, act in every instant when the quality is called for, as though you already had it, and then you will have it",
"It is well to be up before daybreak, for such habits contribute to health, wealth, and wisdom",
"We are what we repeatedly do. Excellence, then is not an act, but a habit",
"Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength.",
"The last three or four reps is what makes the muscle grow. This area of pain divides the champion from someone else who is not a champion. That's what most people lack, having the guts to go on and just say they'll go through the pain no matter what happens",
"The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it, as long as you really believe 100 percent",
"The resistance that you fight physically in the gym and the resistance that you fight in life can only build a strong character",
"Weak dogs bark the loudest",
"Action may not always bring happiness",
"A man wrapped up in himself makes a very small bundle.",
"Diligence is the mother of good luck",
"Every man should be a part of multiple clubs and social groups, if not three. A group of like-minded achievement-oriented individuals can dramatically leverage each other's success to do things otherwise impossible",
"A stupid man's report of what a clever man says can never be accurate, because he unconsciously translates what he hears into something he can understand.",
"Anything you're good at contributes to happiness",
"Father, forgive them; for they know not what they do",
"I can do all things through Him who gives me strength - Philippians 4:13",
"My grace is sufficient for you, for my power is made perfect in weakness. Therefore I will boast all the more gladly about my weaknesses, so that Christ's power may rest on me. That is why, for Christ's sake, I delight in weaknesses, in insults, in hardships, in persecutions, in difficulties. For when I am weak, then I am strong. (2 Cor. 12:9-10)",
"Some pretend to be rich, yet have nothing; others pretend to be poor, yet have great wealth. Proverbs 13:7",
"To the weak I became weak, to win the weak. I have become all things to all people so that by all possible means I might save some  - Corinthians 9:22",
"In order to succeed, your desire for success should be greater than your fear of failure",
"As we look ahead into the next century, leaders will be those who empower others",
"I believe that if you show people the problems and you show them the solutions they will be moved to act",
"Life is not fair",
"Success is a lousy teacher. It seduces smart people into thinking they can't lose. Your most unhappy customers are your greatest source of learning",
"I honestly believe we are all the same. It's condescending to say I will give them what THEY want. You are all a bunch of idiots so I will do things I don't believe in to amuse you",
"Occasionally, people get upset because they don't think it's funny. Somebody asked me Bill why can't you do things that appeal to everybody? ?? well that's impossible! What a burden! I will please all people! No one's done that yet. What am I supposed to do, change my beliefs and attitude for them? To be what to them?",
"The world is like a ride at an amusement park, and when you choose to go on it, you think it's real because that's how powerful our minds are. And the ride goes up and down and round and round; it has thrills and chills and it's very brightly colored and it's very loud and it's fun... for a while. Some people have been on the ride for a long time, and they begin to question: Is this real, or is this just a ride? And other people have remembered, and they come back to us, and they say, Hey - don't worry, don't be afraid -EVER- because, this is just a ride. And we... KILL those people HAHAHA! Shut him up! We have a lot invested in this ride - SHUT HIM UP! Look at my furrows of worry! Look at my big bank account, and my family! This just HAS to be real!... But it's just a ride. And we always kill those good guys who try and tell us that, you ever notice that? And let the demons run amok? Jesus - murdered; Martin Luther King - murdered; Malcolm X - murdered; Gandhi - murdered; John Lennon - murdered; Reagan... wounded HAHA! But it doesn't matter because: It's just a ride. And we can change it anytime we want. It's only a choice. No effort, no work, no job, no savings of money. A choice, right now, between fear and love. The eyes of fear want you to put bigger locks on your doors, buy guns, close yourself off. The eyes of love, instead, see all of us as one. Here's what we can do to change the world, right now, to a better ride: Take all that money that we spend on weapons and defense each year and instead spend it feeding and clothing and educating the poor of the world, which it would many times over, NOT ONE HUMAN BEING EXCLUDED, and we could explore space, together, both inner and outer, forever, in peace.",
"I shall allow no man to belittle my soul by making me hate him",
"All successful people men and women are big dreamers. They imagine what their future could be, ideal in every respect, and then they work every day toward their distant vision.",
"Begin today to practice self-discipline in every area of your life. Persist in this practice until self-discipline comes to you automatically. You make yourself into a better, stronger person by persisting every time you feel like quitting. The greater your self-discipline, the greater your self-confidence and the lower will be your fear of failure and rejection.  When you gain strong self-discipline, you will become unstoppable in your life",
"Courage to face fear is developed with practice. Practice courage whenever courage is required",
"If you would become a success, you must resolve to confront your fears. If you do the things you fear, the death of fear is certain. Do the thing and you will have the power",
"You are the architect of your own destiny; you are the master of your own fate; you are behind the steering wheel of your life. There are no limitations to what you can do, what you can have or who you can be. Except the limitations you place on yourself by your own thinking",
"I would much rather have regrets about not doing what people said, than regretting not doing what my heart led me to and wondering what life had been like if I'd just been myself",
"As you think, so shall you become",
"Don't fear failure. ? Not failure, but low aim, is the crime. In great attempts it is glorious even to fail.",
"I'm not in this world to live up to your expectations and you're not in this world to live up to mine",
"If you always put limit on everything you do, physical or anything else. It will spread into your work and into your life. There are no limits. There are only plateaus, and you must not stay there, you must go beyond them",
"If you spend too much time thinking about a thing, you'll never get it done",
"It's not the daily increase but daily decrease. Hack away at the unessential",
"You just wait. I'm going to be the biggest Chinese Star in the world.",
"A jug fills drop by drop",
"Believe nothing merely because you have been told it...Do not believe what your teacher tells you merely out of respect for the teacher. But whatsoever, after due examination and analysis, you find to be kind, conducive to the good, the benefit, the welfare of all beings -- that doctrine believe and cling to, and take it as your guide.",
"Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment",
"Hatred does not cease by hatred, but only by love; this is the eternal rule",
"He who envies others does not obtain peace of mind",
"He who knows and understands all forgives all",
"He who loves 50 people has 50 woes",
"Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else",
"However many holy words you read, however many you speak, what good will they do you if you do not act on upon them?",
"It is better to conquer yourself than to win a thousand battles. Then the victory is yours. It cannot be taken from you, not by angels or by demons, heaven or hell.",
"The mind is everything. What you think, You become",
"Those who are free of resentful thoughts surely find peace",
"To be idle is a short road to death and to be diligent is a way of life; foolish people are idle, wise people are diligent",
"To enjoy good health, to bring true happiness to one's family, to bring peace to all, one must first discipline and control one's own mind. If a man can control his mind he can find the way to Enlightenment, and all wisdom and virtue will naturally come to him",
"To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear.",
"Virtue is persecuted more by the wicked than it is loved by the good",
"Whatever words we utter should be chosen with care for people will hear them and be influenced by them for good or ill",
"Work out your own salvation. Do not depend on others.",
"You will not be punished for your anger, you will be punished by your anger",
"You, yourself, as much as anybody in the entire universe deserve your love and affection",
"Everything that irritates us about others can lead us to an understanding of ourselves.",
"We read to know that we are not alone",
"Books are the quietest and most constant of friends; they are the most accessible and wisest of counselors, and the most patient of teachers.",
"Failure is unimportant. It takes courage to make a fool of yourself",
"This is a ruthless world and one must be ruthless to cope with it.",
"To truly laugh, you must be able to take your pain, and play with it!",
"Best time to plant a tree was 20 years ago. 2nd best time is now",
"As bad as it hurts, as bad as it burns right now, it will all pay off in the end",
"Everytime we lose, I ask myself what MORE could I have done?",
"I get up so early in the morning to work out coz it takes discipline. It really shows me that, when I get up in the morning, I could easily roll over but instead, I'm like alright let's do it. It's part of the regimen",
"I'm truly blessed to get up every morning and do what I love. If this is the hardest thing I have to endure in my day, then I'm living a pretty good life",
"You can never go somewhere you've never been without doing something you've never done",
"I think what kind of person you are during success is who you are. It's easy to be nice in failure and when you're broke - then you really need a lot of help from people. But after you win some money, that's the person you really are, because now you can be mean to people. You can act like an asshole. I've seen people trip out again and again. A lot of times this behavior, when you're up, will determine if you get another shot someday, because things in this business always go down. I want them to say, He was a nice guy during the whole process. He never did the entourage thing. Because that ain't funny. It's annoying",
"It's extraordinary to me when you get a laugh. That you can go in front of a bunch of people you never met before, you can say some stuff and they all laugh in unison - that's amazing. It's a miracle",
"A room without books is like a body without a soul.",
"Respect your efforts, respect yourself. Self-respect leads to self-discipline. When you have both firmly under your belt, that's real power",
"A superior man is modest in his speech, but exceeds in his actions",
"Better a diamond with a flaw than a pebble without.",
"Choose a job you love, and you will never have to work a day in your life",
"Don't complain about the snow on your neighbor's roof when your own doorstep is unclean",
"If I am walking with two other men, each of them will serve as my teacher. I will pick out the good points of the one and imitate them, and the bad points of the other and correct them in myself",
"Instead of being concerned that you have no office, be concerned to think how you may fit yourself for office. Instead of being concerned that you are not known, be worthy of being known",
"It does not matter how slowly you go as long as you do not stop",
"Old age, believe me, is a good and pleasant thing. It is true you are gently shouldered off the stage, but then you are given such a comfortable front stall as spectator",
"Our greatest glory is not in never falling, but in rising every time we fall",
"People's Natures are alike. It is their habits that carry them far apart",
"Respect yourself and others will respect you",
"Study the past if you would define the future",
"Success depends upon previous preparation, and without such preparation there is sure to be failure.",
"The expectations of life depend upon diligence",
"The faults of a superior person are like the sun and moon. They have their faults, and everyone sees them; they change and everyone looks up to them",
"The firm, the enduring, the simple, and the modest are near to virtue",
"The more man meditates upon good thoughts, the better will be his world and the world at large.",
"The superior man is distressed by the limitations of his ability",
"The way of the superior person is threefold; virtuous, they are free from anxieties; wise they are free from perplexities; and bold they are free from fear.",
"They must often change, who would be constant in happiness or wisdom",
"To be wronged is nothing unless you continue to remember it",
"What the superior person seeks is in themselves. What the small person seeks is in others.",
"Remember that sometimes not getting what you want is a wonderful stroke of luck",
"Any fool can criticize, condemn, and complain - and most fools do",
"Are you bored with life? Then throw yourself into some work you believe in with all your heart, live for it, die for it, and you will find happiness that you had thought could never be yours.",
"Develop success from failures. Discouragement and failure are two of the surest stepping stones to success",
"Do the thing you fear to do and keep on doing it. That is the quickest and surest way ever yet discovered to conquer fear.",
"Flaming enthusiasm, backed up by horse sense and persistence, is the quality that most frequently makes for success",
"Get busy. Your blood with start circulating, your mind will start ticking and this whole positive upsurge of life will drive worry form your mind. Keep busy. It??s the cheapest kind of medicine on this world and one of the best",
"Happiness doesn't depend on any external conditions, it is governed by our mental attitude",
"In his fascinating book, Alone, Admiral Richard E. Byrd told about the time he spent in bewildering and soul-shattering darkness. He lived alone in a shack that was literally buried in the great glacial icecap that covers the South Pole. He spent five months there. The days were as black as the nights. No living creature of any kind existed within a hundred miles. The cold was so intense that he could hear his breath freeze and crystallize as the wind blew it past his ears. At night, before blowing out the lantern, I formed the habit of planning the morrow's work. He had to, in order to preserve his sanity. It was wonderful to be able to dole out time in this way. It brought me an extraordinary sense of command over myself; and without constant activity, the days would have been without purpose; and without purpose, they would have ended ? as such days always end ? in disintegration.",
"Inaction breeds doubt and fear. Action breeds confidence and courage. If you want to conquer fear, do not sit home and think about it. Go out and get busy.",
"It isn't what you have, or who you are, or where you are, or what you are doing that makes you happy or unhappy. It is what you think about",
"Men do not die from overwork. They die from dissipation and worry. Yes, from dissipation of their energies-and worry because they never seem to get their work done",
"Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all",
"Only the prepared speaker deserves to be confident.",
"Peace is found in libraries and laboratories because people are too absorbed in their tasks to worry about themselves. They rarely have nervous breakdowns. They haven't time for such luxuries",
"People rarely succeed unless they have fun in what they are doing",
"Remedy for worry is to get completely occupied doing something constructive",
"Speakers who talk about what life has taught them never fail to keep the attention of their listeners.",
"Take a chance! All life is a chance. The man who goes farthest is generally the one who is willing to do and dare",
"The royal road to a man's heart is to talk to him about the things he treasures most",
"The successful man will profit from his mistakes and try again in a different way",
"The world is full of people who are grabbing and self-seeking. So the rare individual who unselfishly tries to serve others has an enormous advantage. He has little competition",
"When dealing with people, remember you are not dealing with creatures of logic, but creatures of emotion.",
"You can conquer almost any fear if you will only make up your mind to do so. Remember, fear doesn't exist anywhere except in the mind",
"Your purpose is to make your audience see what you saw, hear what you heard, feel what you felt. Relevant detail, couched in concrete, colorful language, is the best way to recreate the incident as it happened and to picture it for the audience",
"It is not the strongest or the most intelligent of the species that survives. It is the one most adaptable to change",
"You feel the way you do right now because of the thoughts you are thinking at this moment.",
"Believe it can be done. When you believe something can be done, really believe, your mind will find the ways to do it. Believing a solution paves the way to solution.",
"Lack of self-confidence is due to mismanaged memory",
"Look at things not as they are, but as they can be. Visualization adds value to everything. A big thinker always visualizes what can be done in the future. He isn't stuck with the present",
"Persons who reach the higher rungs in business management, selling, engineering, religious work, writing, acting & in every other pursuit get there by following conscientiously & continuously a plan for self-development & growth.",
"Do not waste time and energy on trivial matters that do not have a great impact on your life. Focus your attention on your big goals at all times and do not waver",
"The important thing is not being afraid to take a chance. Remember, the greatest failure is to not try",
"If you want to reach a state of bliss, then go beyond your ego and the internal dialogue. Make a decision to relinquish the need to control, the need to be approved, and the need to judge. Those are the three things the ego is doing all the time. It's very important to be aware of them every time they come up",
"Let people say what they want. Let them comment or not comment on what they perceive us to be. Can a block of ice become hot just because someone says so? Does the crow become white just because someone says so? The reality of an object is its reality and does not change because I say it has changed. Similarly let us not be disturbed by the opinions/attitude of people regarding our strengths and weaknesses. Instead, let us focus on our efforts",
"Don't cry because it's over, smile because it happened.",
"The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
"Great spirits have always encountered violent opposition from mediocre minds",
"No one can make you feel inferior without your consent.",
"You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face. You must do the thing which you think you cannot do.",
"The key is to keep company only with people who uplift you, whose presence calls forth your best",
"In the long run, every man will pay the penalty for his own misdeeds. He will reap what he sowed. She will reap what she sowed. The man who remembers this will be angry with no one, offend no one, hate no one, vilify no one",
"If other people do not understand our behavior?so what? Their request that we must only do what they understand is an attempt to control us. If this is being asocial or irrational in their eyes, so be it. Mostly they resent our freedom and our courage to be ourselves. We owe nobody an explanation, as long as our acts do not hurt or infringe on them. How many lives have been ruined by this need to explain, which usually implies that the explanation be understood, i.e. approved. Let your deeds be judged, and from your deeds, your real intentions, but know that a free person owes an explanation only to himself?to his reason and his conscience?and to the few who may have a justified claim for explanation.",
"Whenever you feel like criticizing any one...just remember that all the people in this world haven't had the advantages that you've had.",
"Talent is a flame, Genius is a fire",
"The only thing we have to fear is fear itself",
"Many a book is like a key to unknown chambers within the castle of one??s own self.",
"I honestly think it is better to be a failure at something you love than to be a success at something you hate",
"Children should be taught to question everything they read and hear. They should be taught to question authority. Parents and teachers don't want to teach kids to question authority because they themselves are authority figures. So they don't want to undermine their own bullshit inside the household and classrooms. So they stroke the kid, the kid strokes them, they all stroke each other and they all grow up fucked up and come to shows like this",
"Respect and Obedience should not be automatic. They should be earned",
"We believe in stupid things because we are pounded ideas as children. Kids are too young to argue against ideas from adults. Up to a certain age, kids believe everything grown-ups tell them. EVERYTHING. So they don't learn how to question things. They become adults, they still don't question things",
"A mind needs books as a sword needs a whetstone, if it is to keep its edge.",
"A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.",
"Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
"Look at me. I'm fat, black, can't dance, and I have two gay fathers. People have been messing with me my whole life. I learned a long time ago there's no sense getting all riled up every time a bunch of idiots give you a hard time. In the end, the universe tends to unfold as it should",
"If you only read the books that everyone else is reading, you can only think what everyone else is thinking.",
"Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired, and success achieved",
"Instead of comparing our lot with that of those who are more fortunate than we are, we should compare it with the lot of the great majority of our fellow men. It then appears that we are among the privileged",
"Many persons have a wrong idea of what constitutes true happiness. It is not attained through self-gratification but through fidelity to a worthy purpose.",
"Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence",
"When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.",
"Biggest tasks in the world can be accomplished when they are broken down to enough small steps. And after you've broken them down, just start doing one small step",
"Enthusiasm is the yeast that makes your hopes shine to the stars. Enthusiasm is the sparkle in your eyes, the swing in your gait. The grip of your hand, the irresistible surge of will and energy to execute your ideas",
"It has been my observation that most people get ahead during the time that others waste",
"There are no big problems, there are just a lot of little problems.",
"When everything seems to be going against you, remember that the airplane takes off against the wind, not with it",
"You can't build a reputation on what you are going to do.",
"We judge ourselves by what we feel capable of doing, while others judge us by what we have already done",
"Sometimes you are gonna struggle, sometimes you won't make every shot, sometimes you are going to get your ass handed to you. But that's okay. That's all part of the learning process.",
"Failure meant a stripping away of the inessential. I stopped pretending to myself that I was anything other than what I was, and began to direct all my energy to finishing the only work that mattered to me. Had I really succeeded at anything else, I might never have found the determination to succeed in the one area where I truly belonged. I was set free, because my greatest fear had been realized, and I was still alive, and I still had a daughter whom I adored, and I had an old typewriter, and a big idea. And so rock bottom became a solid foundation on which I rebuilt my life.",
"It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all, in which case you have failed by default",
"You can't wait for inspiration. You have to go after it with a club.",
"Whoever controls the volume of money in our country is absolute master of all industry and commerce...when you realize that the entire system is very easily controlled, one way or another, by a few powerful men at the top, you will not have to be told how periods of inflation and depression originate",
"You think your pain and your heartbreak are unprecedented in the history of the world, but then you read. It was books that taught me that the things that tormented me most were the very things that connected me with all the people who were alive, or who had ever been alive.",
"I am struck by how sharing our weakness and difficulties is more nourishing to others than sharing our qualities and successes.",
"A man's spirit is free, but his pride binds him with chains of suffocation in a prison of his own insecurities",
"Desperation is a necessary ingredient to learning anything, or creating anything. Period. If you ain't desperate at some point, you ain't interesting",
"I know this sounds strange, but as a kid, I was really shy. Painfully shy. The turning point was freshman year, when I was the biggest geek alive. No one, I mean no one, even talked to me",
"If I had never ventured beyond being a stand-up comic, then I would be sitting in my house today working on my Leonardo DiCaprio impression",
"If you aren't in the moment, you are either looking forward to uncertainty, or back to pain and regret.",
"Discipline is the bridge between goals and accomplishment",
"If you are not willing to risk the unusual, you will have to settle for the ordinary",
"If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much",
"If you don't like how things are, change it! You're not a tree",
"It doesn't matter which side of the fence you get off on sometimes. What matters most is getting off. You cannot make progress without making decisions.",
"Success is nothing more than a few simple disciplines, practiced every day.",
"Success is steady progress toward one's personal goals",
"Take advantage of every opportunity to practice your communication skills so that when important occasions arise, you will have the gift, the style, the sharpness, the clarity, and the emotions to affect other people",
"Take time to gather up the past so that you will be able to draw from your experience and invest them in the future",
"The difficulties you meet will resolve themselves as you advance. Proceed, and light will dawn, and shine with increasing clearness on your path",
"The few who do are the envy of the many who only watch",
"The major reason for setting a goal is for what it makes of you to accomplish it. What it makes of you will always be the far greater value than what you get",
"The walls we build around us to keep sadness out also keeps out the joy",
"The worst thing one can do is not to try, to be aware of what one wants and not give in to it, to spend years in silent hurt wondering if something could have materialized - never knowing",
"There are only 3 colors, 10 digits, and 7 notes; it's what we do with them that's important",
"Things that I felt absolutely sure of but a few years ago, I do not believe now. This thought makes me see more clearly how foolish it would be to expect all men to agree with me",
"We must all suffer one of two things: the pain of discipline or the pain of regret and disappointment",
"When you know what you want, and want it bad enough, you will find a way to get it.",
"Whoever renders service to many puts himself in line for greatness - great wealth, great return, great satisfaction, great reputation, and great joy",
"Without a sense of urgency, desire loses its value",
"Work harder on yourself than you do on your job.",
"You cannot change your destination overnight, but you can change your direction overnight",
"You've got to be a dreamer. You've got to envision the future. You've got to see California while you're climbing 14,000-foot peaks. You've got to see the finish line while you're running the race. You've got to hear the cheers when you're in the middle of a monster project. And you've got to be willing to put yourself through the paces of doing the uncomfortable until it becomes comfortable, because that's how you realize your dreams",
"Daring ideas are like chessmen moved forward; they may be beaten, but they may start a winning game",
"Go to foreign countries and you will get to know the good things one possesses at home",
"It seems to never occur to fools that merit and good fortune are closely united",
"Talent develops in quiet places, character in the full current of human life.",
"The person born with a talent they are meant to use will find their greatest happiness in using it",
"Thinking is easy, acting is difficult, and to put one's thoughts into action is the most difficult thing in the world",
"I still find each day too short for all the thoughts I want to think, all the walks I want to take, all the books I want to read, and all the friends I want to see",
"Do not pray for easy lives. Pray to be stronger men.",
"When written in Chinese, the word crisis is composed of two characters. One represents danger and the other represents opportunity",
"Stop judging the life you have lived and get on with the life you still may live. Whatever mistakes you have made and no matter how many regrets may litter your past, plant a new tree today",
"You do the work and you want people to see it; but while I'm doing the work, the result doesn't matter at all to me. Ultimately, I don't, I don't care whether the film is - you know - some big giant box-office bonanza and I don't care if its a complete flop. To me, when a film gets made and it's actually finished it's a success. They're all a success in their own way",
"Reading is the sole means by which we slip, involuntarily, often helplessly, into another's skin, another's voice, another's soul.",
"You cannot judge any man beyond your knowledge of him, and how small is your knowledge",
"An ant on the move does more than a dozing ox",
"Anticipate the difficult by managing the easy.",
"Boasting of wealth and virtue brings your demise",
"By not exalting the great, by not flaunting materials, by putting what is desirable out of sight, people's hearts will remain undisturbed and without envy, anger or desire",
"Care about what other people think and you will always be their prisoner.",
"Going forward seems like retreat",
"Great acts are made up of small deeds. A journey of a thousand miles must begin with a single step",
"Great talents ripen late",
"He who knows himself is enlightened",
"He who knows, does not speak. He who speaks, does not know",
"If you would take, you must first give, this is the beginning of intelligence",
"In the world there is nothing more submissive and weak than water. Yet for attacking that which is hard and strong nothing can surpass it",
"Manifest plainness, embrace simplicity, reduce selfishness, have few desires",
"Must I fear what others fear? What nonsense! Other people live as if they will be the last one to miss the biggest party. Other have more than enough, I alone seem to have nothing. I am content to be a fool. I alone am different  Others are practical and bright. I alone seem dim and weak. Others are sharp and clever. I alone seem dull and stupid. I drift like the waves of the sea. Without direction, like the restless wind. But I am nourished by the great Mother.",
"Nature does not hurry, yet everything is accomplished.",
"One can not reflect in streaming water. Only those who know internal peace can give it to others",
"The higher the sun arises, the less shadow he casts;  the greater the goodness, the less it covets praise; yet it cannot avoid its rewards in honours",
"The one with deep virtue does not contend with people. Thus, he becomes above reproach",
"The softest things in the world overcome the hardest things in the world",
"The wise man does not lay up his own treasures. The more he gives to others, the more he has for his own.",
"The words of truth are always paradoxical.",
"To know yet to think that one does not know is best",
"To lead people walk behind them",
"To the mind that is still, the whole universe surrenders.",
"When you are content to be simply yourself and don't compare or compete, everybody will respect you.",
"Wise men speak because they have something to say.  Fools because they have to say something",
"Know that you possess the strong, masculine principle but abide by the meek, feminine principle. The one who does not contend with others flows with nature like water",
"The great rivers and seas are kings of all mountain streams because they skillfully stay below them. That is why they can be their kings. Therefore, in order to be the superior of the people / One must, in the use of words, place himself below them. And in order to be ahead of the people, one must, in one's own person, follow them. Therefore the sage places himself above the people and they do not feel his weight. He places himself in front of them and the people do not harm him. Therefore the world rejoices in praising him without getting tired of it. It is?precisely?because he does not compete, that the world cannot compete with him.",
"I have no time to quarrel, no time for regrets and no man can force me to stoop low enough to hate him. Can??t you see I??m busy trying to educate the poor?",
"Smile! It will please your friends and infuriate your enemies",
"Everyone thinks of changing the world, but no one thinks of changing himself",
"The two strongest warriors in this world are Time and Patience",
"If you can do what you do best and be happy, you're further along in life than most people",
"School, I never truly got the knack of. I could never focus on things I didn't want to learn",
"He gets down to the end of his life, and he looks back and decides that all those years he suffered, Those were the best years of his life, 'cause they made him who he was. All those years he was happy? You know, total waste. Didn't learn a thing. So, if you sleep until you're 18... Ah, think of the suffering you're gonna miss. I mean high school? High school-those are your prime suffering years. You don't get better suffering than that.",
"An effort made for the happiness of others lifts above ourselves.",
"Everyone sees what you appear to be but a few really know what you are",
"You want society to accept you, but you can't even accept yourself",
"A man is the product of his thoughts. What he thinks, he becomes",
"A small body of determined spirits fired by an unquenchable faith in their mission can alter the course of history",
"Always aim at complete harmony of thought and word and deed. Always aim at purifying your thoughts and everything will be well",
"Be the change that you wish to see in the world",
"Each one has to find his peace from within. And peace to be real must be unaffected by outside circumstances.",
"Happiness is when what you think, what you say, and what you do are in harmony",
"I will not let anyone walk through my mind with their dirty feet",
"If I had no sense of humor, I would long ago have committed suicide",
"The best way to find yourself is to lose yourself in the service of others",
"The weak can never forgive. Forgiveness is the attribute of the strong",
"Failure is success if we learn from it",
"Don't be in a hurry to condemn because he doesn't do as you think or think as you think or as fast. There was a time when you didn't know what you know today",
"My alma mater was books, a good library.... I could spend the rest of my life reading, just satisfying my curiosity.",
"How much time he saves who does not look to see what his neighbor says or does or thinks.",
"I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinions of himself than on the opinions of others.",
"If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment",
"The best revenge is to be unlike him who performed the injury.",
"You have power over your mind - not outside events. Realize this, and you will find strength",
"Virtue is a habit of the mind, consistent with moderation and reason",
"Today a reader, tomorrow a leader.",
"Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.",
"Disciplining yourself to do what you know is right and important, although difficult, is the highroad to pride, self-esteem, and personal satisfaction",
"I believe that everything happens for a reason. People change so that you can learn to let go, things go wrong so that you appreciate them when they're right, you believe lies so you eventually learn to trust no one but yourself, and sometimes, good things fall apart so better things can fall together.",
"A man cannot be comfortable without his own approval",
"Anger is an acid that can do more harm to the vessel in which it is stored than to anything on which it is poured",
"Good friends, good books, and a sleepy conscience: this is the ideal life.",
"I have never let my schooling interfere with my education",
"It usually takes me more than three weeks to prepare a good impromptu speech",
"The secret of getting ahead is getting started. The secret of getting started is breaking your complex overwhelming tasks into small manageable tasks, and starting on the first one.",
"The secret source of humor itself is not joy but sorrow. There is no humor in heaven",
"What a wee little part of a person's life are his acts and his words! His real life is led in his head, and is known to none but himself.",
"Don't wait until everything is just right. It will never be perfect. There will always be challenges, obstacles and less than perfect conditions. So what. Get started now. With each step you take, you will grow stronger and stronger, more and more skilled, more and more self-confident and more and more successful.",
"Every man must decide whether he will walk in the light of creative altruism or in the darkness of destructive selfishness",
"Freedom is never voluntarily given by the oppressor",
"Human salvation lies in the hands of the creatively maladjusted",
"I believe that unarmed truth and unconditional love will have the final word in reality",
"The hottest place in hell is reserved for those who remain neutral in times of great moral conflict",
"There are no accidents",
"Yesterday is history, tomorrow is mystery. But today is a gift. That's why we call it the Present",
"Your mind is like water. When it is agitated, it becomes difficult to see. But if you allow it to settle, the answer becomes clear",
"When you hate, the only one that suffers is you. Because most of the people you hate don't know it and the rest don't care",
"I've failed over and over and over again in my life and that is why I succeed.",
"You have to expect things of yourself before you can do them",
"A wise man is superior to any insults which can be put upon him, and the best reply to unseemly behavior is patience and moderation",
"What happened happened and could not have happened any other way",
"Kind words can be short and easy to speak but their echoes are truly endless.",
"He who is not courageous enough to take risks will accomplish nothing in life",
"I am the greatest, I said that even before I knew I was",
"I hated every minute of training, but I said, Don't quit. Suffer now and live the rest of your life as a champion.",
"It's lack of faith that makes people afraid of meeting challenges, and I believed in myself",
"It's the repetition of affirmations that leads to belief. And once that belief becomes a deep conviction, things begin to happen.",
"Only a man who knows what it is like to be defeated can reach down to the bottom of his soul and come up with the extra ounce of power it takes to win when the match is even",
"The man who has no imagination has no wings.",
"What keeps me going is goals",
"Imagination rules the world.",
"The word impossible is not in my dictionary",
"Before success comes in any man's life, he is sure to meet with much temporary defeat, and, perhaps, some failure. When defeat overtakes a man, the easiest and most logical thing to do is to quit. That is exactly what the majority of men do. More than five hundred of the most successful men this country has ever known told the author their greatest success came just one step beyond the point at which defeat had overtaken them.",
"Do not wait: the time will never be 'just right'. Start where you stand, and work whatever tools you may have at your command and better tools will be found as you go along.",
"Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit.",
"First comes thought; then organization of that thought, into ideas and plans; then transformation of those plans into reality. The beginning, as you will observe, is in your imagination.",
"Set your mind on a definite goal and observe how quickly the world stands aside to let you pass.",
"The starting point of all achievement is DESIRE. Keep this constantly in mind. Weak desire brings weak results, just as a small fire makes a small amount of heat.",
"The strongest oak of the forest is not the one that is protected from the storm and hidden from the sun. It's the one that stands in the open where it is compelled to struggle for its existence against the winds and rains and the scorching sun.",
"When defeat comes, accept it as a signal that your plans are not sound, rebuild those plans, and set sail once more toward your coveted goal.",
"Stress is an ignorant state. It believes that everything is an emergency. Nothing is that important.",
"It always seems impossible until it is done.",
"Don't just bear with pain but love it. Our misfortunes will help us unexpectedly",
"Shedding one's skin. The snake that cannot shed its skin perishes. So do the spirits who are prevented from changing their opinions",
"Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy",
"It's always too early to quit",
"What you plant now, you will harvest later.",
"All men who have achieved great things have been great dreamers.",
"Always forgive your enemies; nothing annoys them so much.",
"It's good to have goals and dreams, but while you're waiting for things to change, waiting for promises to come to pass, don't be discontent with where you are. Learn to enjoy the season that you're in",
"Be brave. Take risks. Nothing can substitute experience.",
"Don't think about what you've left behind The alchemist said to the boy as they began to ride across the sands of the desert. If what one finds is made of pure matter, it will never spoil. And one can always come back. If what you had found was only a moment of light, like the explosion of a star, you would find nothing on your return.",
"Every second of the search is an encounter with God. When I have been truly searching for my treasure, every day has been luminous...I've discovered things along the way that I never would have seen had I not had the courage to try things that seemed impossible for a shepherd to achieve. - The Alchemist",
"I had this dream to become a writer since I was a teenager",
"I was not encouraged to follow the career of a writer because my parents thought that I was going to starve to death. They thought nobody can make a living from being a writer in Brazil. They were not wrong.",
"Making a decision was only the beginning of things. When someone makes a decision, he is really diving into a strong current that will carry him to places he had never dreamed of when he first made the decision.",
"No reason is needed for loving.",
"People are afraid to pursue their most important dreams, because they feel that they don't deserve them, or that they'll be unable to achieve them.",
"Tell your heart that the fear of suffering is worse than the suffering itself. And that no heart has ever suffered when it goes in search of its dreams.",
"That's what Alchemists do. They show that when we strive to become better than we are, everything around us becomes better, too. - The Alchemist",
"The world's greatest lie is that at a certain point in our lives, we lose control of what's happening to us, and our lives become controlled by fate. That's the world's greatest lie. - The Alchemist",
"There is only one way to learn. It's through action. Everything you need to know you have learned through your journey.",
"There is suffering in life, and there are defeats. No one can avoid them. But it's better to lose in the struggles for your dreams than to be defeated without ever knowing what you're fighting for",
"We can never judge the lives of others, because each person knows only their own pain. It's one thing to feel that you are on the right path, but it's another to think that yours is the only path",
"When a person really desires something, the entire universe conspires to help you achieve it",
"When you possess great treasures within you and try to tell others of them, seldom are you believed.",
"Whoever you are, or whatever it is that you do, when you really want something, it's because that desire originated in the soul of the universe. It's your mission on earth. - The Alchemist",
"You can't go back, you have to worry only about the best way of moving forward",
"You have to take risks. We will only understand the miracle of life fully when we allow the unexpected to happen.",
"Follow effective action with quiet reflection. From the quiet reflection will come even more effective action",
"One person with a belief is equal to a force of ninety-nine who have only interests",
"Some day, in years to come, you will be wrestling with the great temptation, or trembling under the great sorrow of your life. But the real struggle is here, now, in these quiet weeks. Now it is being decided whether, in the day or your supreme sorrow or temptation, you shall miserably fail or gloriously conquer. Character cannot be made except by a steady, long-continued process.",
"Be kind, for everyone you meet is fighting a hard battle.",
"Do the things you fear, and the death of fear is certain",
"Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in",
"I cannot remember the books I've read any more than the meals I have eaten; even so, they have made me.",
"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
"He who learns to let to go of his problems instead of fighting them with all his might learns how to flow with the harmony of life",
"I became a performer because it was what I enjoyed doing",
"I know that if I wasn't scared, something's wrong, because the thrill is what's scary",
"If I thought about it, I could be bitter, but I don't feel like being bitter. Being bitter makes you immobile, and there's too much that I still want to do.",
"There was a time in my life when I thought I had everything - millions of dollars, mansions, cars, nice clothes, beautiful women, and every other materialistic thing you can imagine. Now I struggle for peace",
"When you ain't got no money, you gotta get an attitude",
"It is during the worst times of your life that you will get to see the true colors of the people who say they care for you",
"Each time a man stands up for an ideal, or acts to improve the lot of others, or strikes out against injustice, he sends forth a tiny ripple of hope, and crossing each other from a million different centers of energy and daring, those ripples build a current which can sweep down the mightiest walls of oppression and resistance.",
"It doesn't matter how this looks to other people, it matters how it looks to you. If this is something you wanna do and if this is something you gotta do, then you do it. Fighters fight",
"The world ain't all sunshine and rainbows. It's a very mean and nasty place and I don't care how tough you are, it will beat you down to your knees and keep you there permanently if you let it. You, me, or nobody's gonna hit as hard as life. But it ain't about how hard ya hit. It's about how hard you can get hit and keep moving forward. How much you can take and keep moving forward. That's how winning is done! Now if you know what you're worth, then go out and get what you're worth. But ya gotta be willing to take the hits, and not pointing fingers saying you ain't where you wanna be because of him, or her, or anybody! Cowards do that and that ain't you! You're better than that!",
"Comedy is like boxing. All those little Open Mics are just little fighters that you're fighting along the way to get to the title",
"Success has a simple formula: do your best, and people may like it.",
"God Himself, sir, does not propose to judge a man until his life is over.  Why should you and I?",
"It is not because things are difficult that we do not dare, it is because we do not dare that they are difficult.",
"Sit down and put down everything that comes into your head and then you're a writer. But an author is one who can judge his own stuff's worth, without pity, and destroy most of it.",
"The only real wisdom is knowing you know nothing",
"Success is 99 percent failure",
"Begin with the end in mind. If you know your destination, you can better understand where you are now. And then you can make the decision to get yourself moving forward in the right direction",
"If you visualize the wrong thing, you'll produce the wrong thing",
"Live out of your imagination instead of your memory. Live your limitless potential instead of your limiting past. You are your own creator",
"Look at the weaknesses of others with compassion, not accusation. It's not what they're not doing or should be doing that's the issue. The issue is your own chosen response to the situation",
"Next to physical, the greatest need of a human being is psychological survival -- to be understood, to be affirmed, to be validated, to be appreciated",
"One person's success is not achieved at the expense or exclusion of the success of others",
"People who exercise their embryonic freedom day after day will, little by little, expand that freedom.  People who do not will find that it withers until they are literally being lived. They are acting out the scripts written by parents, associates, and society",
"Think of a problem you have in your life right now. Identify the first step you can take in your Influence to solve it and then take that step",
"Write down the result you desire. Then write down the actions that will get you to that result. Then do those things",
"Books are the perfect entertainment: no commercials, no batteries, hours of enjoyment for each dollar spent. What I wonder is why everybody doesn't carry a book around for those inevitable dead spots in life.",
"When asked, How do you write? I invariably answer, One word at a time, and the answer is invariably dismissed. But that is all it is. It sounds too simple to be true, but consider the Great Wall of China, if you will: one stone at a time, man. That's all. One stone at a time. But I've read you can see that motherfucker from space without a telescope.",
"I didn't see it then, but it turned out that getting fired from Apple was the best thing that could have ever happened to me. The heaviness of being successful was replaced by the lightness of being a beginner again, less sure about everything. It freed me to enter into one of the most creative periods of my life. I'm pretty sure none of Pixar or the most creative things I've accomplished in life would have happened if I hadn't been fired from Apple. It was awful tasting medicine, but I guess the patient needed it. Sometimes life hits you in the head with a brick. Don't lose faith",
"I have looked in the mirror every morning and asked myself: If today were the last day of my life, would I want to do what I am about to do today? And whenever the answer has been No for too many days in a row, I know I need to change something.",
"I was a college drop-out, my biological parents didn't love me, had no money in my early 20s. I just followed where my natural curiosity and instincts led me. I had no idea why certain things were happening in my life. But you cannot connect the dots looking forward; you can only connect the dots looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something ? your gut, destiny, God, karma, whatever. This approach has never let me down, and it has made all the difference in my life",
"We're always thinking about new markets we could enter, but it's only by saying no that you can concentrate on the things that are really important.",
"When you grow up you tend to get told that the world is the way it is and your life is just to live your life inside the world. Try not to bash into the walls too much. Try to have a nice family, have fun, save a little money. That's a very limited life. Life can be much broader once you discover one simple fact: Everything around you that you call life was made up by people that were no smarter than you and you can change it, you can influence it, you can build your own things that other people can use.",
"You know, my main reaction to this money thing is that it's humorous, all the attention to it, because it's hardly the most insightful or valuable thing that's happened to me",
"You've got to find what you love. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it. And, like any great relationship, it just gets better and better as the years roll on. So keep looking until you find it. Don't settle.",
"Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma - which is living with the results of other people's thinking. Don't let the noise of others' opinions drown out your own inner voice. And most important, have the courage to follow your heart and intuition",
"I learned more about life and myself in the first few years out of school than 15 years of public schooling combined",
"Believe you can and you're halfway there",
"Do what you can, with what you have, where you are.",
"What a blessing it is to love books as I love them;- to be able to converse with the dead, and to live amidst the unreal!",
"Discontent is the first necessity of progress",
"I never did a day's work in my life. It was all fun",
"There is no expedient to which a man will not resort to avoid the real labor of thinking",
"Determine never to be idle. No person will have occasion to complain of lack of time who never loses any. It is wonderful how much may be done if we are always doing",
"Do you want to know who you are? Don't ask. Act! Action will delineate and define you",
"I cannot live without books.",
"That which we obtain too easily, we esteem too lightly. It is dearness only which gives everything its value. Heaven knows how to put a proper price on its goods",
"For every thousand hacking at the leaves of evil, there is one striking at the root",
"Ask yourself What are you waiting for? If you say better timing the answer is you are afraid. Measure the cost of inaction. Understand the unlikelihood of mistakes and missteps ruining your life and do what successful people do: Action",
"If there's a book that you want to read, but it hasn't been written yet, then you must write it.",
"A real decision is measured by the fact that you've taken a new action. If there's no action, you haven't truly decided. You see, in life, lots of people know what to do, but few people actually do what they know. Knowing is not enough! You must take action.",
"I challenge you to make your life a masterpiece. I challenge you to join the ranks of those people who live what they teach, who walk their talk",
"If you want to be successful, find someone who has achieved the results you want and copy what they do and you'll achieve the same results",
"In essence, if we want to direct our lives, we must take control of our habits. It's not what we do once in a while that shapes our lives, but what we do consistently",
"It is in your moments of decision that your destiny is shaped.",
"It's not the events of our lives that shape us, but our beliefs as to what those events mean",
"Most people have no idea of the giant capacity we can immediately command when we focus all of our resources on mastering a single area of our lives",
"One reason so few of us achieve what we truly want is that we never direct our focus; we never concentrate our power. Most people dabble their way through life, never deciding to master anything in particular",
"Passion is the genesis of genius",
"People are not lazy. They simply have impotent goals - that is, goals that do not inspire them",
"People are rewarded in public for what they practice for 10 years in private",
"Setting goals is the first step in turning the invisible into the visible.",
"Take control of your consistent emotions and begin to consciously and deliberately reshape your daily experience of life",
"The secret of success is learning how to use pain and pleasure instead of having pain and pleasure use you. If you do that, you're in control of your life. If you don't, life controls you.",
"The truth is that we can learn to condition our minds, bodies, and emotions to link pain or pleasure to whatever we choose. By changing what we link pain and pleasure to, we will instantly change our behaviors",
"What simple action could you take today to produce a new momentum toward success in your life? How am I going to live today in order to create the tomorrow I'm committed to?",
"You see, it's never the environment; it's never the events of our lives, but the meaning we attach to the events - how we interpret them - that shapes who we are today and who we'll become tomorrow.",
"Accomplish but do not boast, accomplish without show, accomplish without arrogance, accomplish without grabbing, accomplish without forcing",
"Almost all the benefit of the exercise comes at the very end. I'm trying to build strength. And that doesn't happen until the muscle fiber ruptures and the nerve fiber registers the pain. Then nature overcompensates and within 48 hours, the fiber is made stronger",
"Distance lends perspective. A fish does not know that it's wet.",
"Do what you feel in your heart to be right for you will be criticized anyway.",
"Doubt yourself and you doubt everything you see and feel.",
"Great athletes don't let missed shots bother them on the next shot. Remember that you did the best with your ability at the time, learn from it and move on. ",
"Have the courage to leap toward your dream but have the discipline to keep going when the going gets tough",
"How can great happiness and miracles be given away like commodities to those without effort and passion?   In this way, God rewards the hard-working and gives the rest ordinary lives",
"I am what I am today because of the choices I made yesterday",
"I'd rather be at the bottom of a ladder I want to be on than halfway up a ladder I don't want to be on",
"If they understood everything you said, they'd be you. If you understood everything they said, you would be them",
"If you get your head above the crowd, you are going to be criticized. So get used to it.",
"If you have a fucked-up map, every step you take will get you to the wrong place faster",
"Insanity is doing the same thing, over and over again, but expecting different results.",
"Lord, grant me the strength to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference",
"Most great people have attained their greatest success just one step beyond their greatest failure.",
"Never be bothered by what people say as long as you know in your heart you are right",
"No pain, no gain",
"Our ideas, dreams, thoughts are physical things in the universe. If we picture something, if we dream something, and we command and demand from the universe, the universe has no option but to help us.",
"People are often unreasonable and self-centered. Forgive them anyway. If you are kind, people may accuse you of ulterior motives. Be kind anyway. If you are honest, people may cheat you. Be honest anyway. If you find happiness, people may be jealous. Be happy anyway. The good you do today may be forgotten tomorrow. Do good anyway. Give the world the best you have and it may never be enough. Give your best anyway. For you see, in the end, it is between you and God. It was never between you and them anyway.",
"Picture your great self in the future. The competent, lovable person you desire to be. That thought will transform you into that very individual. Thought is supreme. All things come through desire and thought. We become like that on which our hearts are fixed.",
"Reveal your weaknesses, loudly admit your weaknesses and be intentionally vulnerable. Don??t try to be strong, intelligent and superior. Gladly act weak and foolish",
"Sow a thought and you reap an action. Sow enough actions, and you reap a habit. Sow enough habits and you reap a character. Sow a character and you reap a destiny.",
"That which is most personal is most general. The more authentic you become, the more genuine in your expression, particularly regarding personal experiences and even self-doubts, the more people can relate to your expression and the safer it makes them feel to express themselves.",
"The greatest battles of life are fought out daily in the silent chambers of the soul. If you find victory there, love, peace, acceptance and success will follow naturally.",
"The more you take responsibility for your past and present, the more you are able to create the future you seek.",
"This too shall pass",
"Those who mind don't matter, and those who matter don't mind",
"Those who think they know everything are limited by their ego. Only those who are humble enough to admit ignorance are the wisest because they will never stop growing",
"Wise men, when in doubt whether to speak or to keep quiet, give themselves the benefit of the doubt, and remain silent.",
"You can turn yourself into gold. If you just believe.",
"We read books to find out who we are. What other people, real or imaginary, do and think and feel... is an essential guide to our understanding of what we ourselves are and may become.",
"Try a thing you haven't done three times. Once, to get over the fear of doing it. Twice, to learn how to do it. And a third time to figure out whether you like it or not",
"All the adversity I've had in my life, all my troubles and obstacles, have strengthened me ... You may not realize it when it happens, but a kick in the teeth may be the best thing in the world for you",
"If you can dream it, you can do it.",
"There is more treasure in books than in all the pirates' loot on Treasure Island and best of all, you can enjoy these riches every day of your life.",
"Being realistic is the mostly commonly traveled road to mediocrity. What's the point of being realistic? It's unrealistic to invent light bulbs, invent airplanes, be a millionaire ... 99% of people said those things weren't real, unrealistic. As soon as you make the decision to do it, then you just MADE it real. Nothing is unrealistic",
"Don't let anybody tell you, you can't do something. Not even your parents or family. You got a dream, you gotta protect it. People can't do something themselves, they want to tell you you can't do it. If you want something, go get it, PERIOD.",
"In my mind, I've always been an A-list Hollywood superstar. Y'all just didn't know yet",
"Just decide. What you are going to do, who you are going to be, how you are going to do it, just decide. And then the Universe will give it to you.",
"You don't start saying I want to be build the biggest, greatest wall in the history of all great walls. You don't start there. You start by ONE BRICK and decide I'm going to lay this one brick today as perfect as this one brick can be laid. And you lay that one brick every single day. Before you know it, you have the Great wall.",
"A warm smile is the universal language of kindness.",
"Feeling gratitude and not expressing it is like wrapping a present and not giving it",
"Here is the secret of inspiration: Tell yourself that thousands and tens of thousands of people, not very intelligent and certainly no more intelligent than the rest of us, have mastered problems as difficult as those that now baffle you",
"Action seems to follow feeling but really action and feeling go together, and by regulating the action which is under the more direct control of the will, we can indirectly  regulate the feeling, which  is not. So the voluntary path to cheerfulness is to sit up cheerfully and to act and speak as if cheerfulness were already there",
"Be willing to have it so. Acceptance of what has happened is the first step in overcoming the consequences of any misfortune or mistake",
"Belief creates the actual fact",
"If there is any kindness I can show, or any good thing I can do to any fellow being, let me do it now, and not deter or neglect it, as I shall not pass this way again.",
"A great book should leave you with many experiences, and slightly exhausted at the end. You live several lives while reading.",
"Criticism may not be agreeable, but it is necessary. It fulfills the same function as pain in the human body. It calls attention to an unhealthy state of things.",
"Success consists of going from failure to failure without loss of enthusiasm"];
    }

}